### ISSUE TITLE
Examples in Parameter Objects can appear in multiple places

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1032]
## Describe the bug

An example for a parameter could show up in the schema, or in the parameter object (next to schema). Either are equally valid.

```
/params:
  get:
    parameters:
      - name: single-example-good
        description: Valid to its schema
        in: query
        schema: 
          type: string
          enum: [foo, bar]
        example: foo

      - name: single-schema-example-good
        description: Valid to its schema
        in: query
        schema: 
          type: string
          enum: [foo, bar]
          example: foo
```

We currently do not support these sorts of examples, which are showing up in the Digital Ocean example. 

![image](https://user-images.githubusercontent.com/67381/114068707-192fa000-9896-11eb-870e-908a1639818f.png)

## To Reproduce

1. Given the Digital Ocean example https://elements-demo.stoplight.io/?spec=https://raw.githubusercontent.com/digitalocean/openapi/main/specification/DigitalOcean-public.v2.yaml
2. Look at the rate limit headers
3. Should see example, but its not there

## Expected behavior

- ratelimit-limit should have example 5000
- ratelimit-remaining should have example 4816

**Comment by marcelltoth** [comment]
We have worked with `http-spec` before, I think we would be comfortable taking this in any sprint, without external help even (with a non-particularly-high point number). As `http-spec` does not have a dedicated owner, IMO this should be decided based on the expected workload of the teams. If you'd like us to take it, @philsturgeon please place it on our _Product backlog_ where appropriate.

**Comment by mpodlasin** [comment]
This is partially solved in https://github.com/stoplightio/elements/pull/1654

```
      - name: single-example-good
        description: Valid to its schema
        in: query
        schema: 
          type: string
          enum: [foo, bar]
        example: foo
```

will now work.

However this:

```
      - name: single-schema-example-good
        description: Valid to its schema
        in: query
        schema: 
          type: string
          enum: [foo, bar]
          example: foo
```

is a bit trickier. Spec for JSON Schema only mentions "examples" parameter (plural). https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.9.5

There is no mention of "example" (singular).

Even in TypeScript we don't have access to "example" property, since `http-spec` claims we are getting a `JSONSchema7` instance.

So should "example" (singular) parameter in JSON Schema be even supported? 

@marbemac @philsturgeon
