### ISSUE TITLE
Server URL path is removed when sending request from TryIt component

### ISSUE THREAD

**Issue by cormack** [stoplightio/elements#1260]
## Describe the bug
When sending a request from within the TryIt component, the path of the resolved serverUrl is removed.

## To Reproduce

```yaml
servers:
  - url: 'http://localhost/api/{location}'
    variables:
      location:
        default: eu
paths:
  '/categories':
# ......
```

## Expected behavior

It's expected that request is sent to **http://localhost/api/eu/categories**.

Actual request is sent to **http://localhost/categories**.

## Additional context
Problem occurs in 7.0.0-beta.**2**, works as expected in 7.0.0-beta.**1**.

This [line](https://github.com/stoplightio/elements/blob/f366988f9c37e1c1e9f680cc10ef5ff2caab2a61/packages/elements-core/src/components/TryIt/build-request.ts#L58) (seen in code example below) removes the server path through use of **absoluteTo** function.

```typescript
const url = new URL(URI(expandedPath).absoluteTo(serverUrl).toString());
```

This example below makes it work, but not (yet) being an open source contributor I better leave it in other contributors very capable hands.

```typescript
const url = new URL(URI(serverUrl).segment(segment).toString());
```

Keep up the great work!
