### ISSUE TITLE
Prefilled Auth token for "Try It" feature

### ISSUE THREAD

**Issue by bzmw** [stoplightio/elements#1400]
## User story.

As an owner of API documentation, I can pass in an Authorization Token in React, so that Customers of my API Documentation can use the "TryIt" functionality without having to search for an API key of their own.

## Describe the solution you'd like

On instantiation of the `StoplightProject` component I would like to pass in a value. 
Ex:
```
<StoplightProject
  sampleAuth="my-sample-auth-token"
  ...
</StoplightProject>
```

## Comments

This is definitely something that I need for my API Reference, our clients are external to my company and definitely do not want to go digging for an API Token.
If this isn't going to prioritized I think I'll end up hacking it in through some React magic for my specific use case.

**Comment by philsturgeon** [comment]
This is a great idea, but it will be tricky to plan out. 

There can be many different types of auth, maybe multiple used at the same time. Give this OAS:

```
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
```

What would the HTML look like for it?

I dont know if we can do dynamic attribute names:

```html
<elements-stoplight-project
  ApiKeyAuthValue="my-sample-auth-token"
  ...
</elements-stoplight-project>
```

Maybe we could try some sort of special syntax:

```html
<elements-stoplight-project
  parameters="ApiKeyAuth:my-sample-auth-token"
  ...
</elements-stoplight-project>
```

Or... something like that. That would predefine values for _any_ parameters then, but it looks a bit odd, and might have a rough time with multiple values. 

The JS interface is easier, we'd just pass an object:

```js
<StoplightProject
  parameters={{ ApiKeyAuth: "my-sample-auth-token" }}
  ...
</StoplightProject>
```

Anyway, curious what you think about this.

@marcelltoth any ideas on your end?

**Comment by bzmw** [comment]
Personally I prefer the special syntax in your second example because it matches closest to the JS interface.

-----
It's not super awesome but could we throw in some custom fields into the OAS to support something like this?
```
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      x-sample-token: my-sample-auth-token
...
```
