### ISSUE TITLE
Dark Mode Option

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1439]
## User story.

As an API/StoplightProject component user, I can do enable "dark mode", so that I can have dark mode.

## Is your feature request related to a problem?

We technically do have support for it, but we've not created a user facing config option as it's not quite the right colors. @noor-ahmad if you could help us get dark mode looking brilliant, we can get dark mode into the hands of our eager users! 

## Describe the solution you'd like

```
<elements-api darkMode />
<elements-stoplight-project darkMode />
```

**Comment by noor-ahmad** [comment]
Yes, would love to help out with dark mode enhancements! Going to assign myself to this ticket and create a followup for implementation. We want this done for Elements 7.1, right?

**Comment by philsturgeon** [comment]
Yeah we’ve got some time, but can get it out in a 7.0.x if we get the work done sooner.

--
Phil Sturgeon
Product @ Stoplight.io

**Comment by owen-caulfield** [comment]
Any news on this?

**Comment by philsturgeon** [comment]
Passing this one over to @mnaumanali94.

**Comment by jensljungblad** [comment]
Would be cool!

**Comment by callicles** [comment]
Looks like the work has been done and is just missing the stacked layout: ref https://github.com/stoplightio/elements/pull/1366 would be great to get this across the finish line :)

**Comment by TekExplorer** [comment]
How is this going? It seems to me like its implemented, but not exposed? I would love to be able to use the web component with dark mode!

**Comment by KaranTrivedi** [comment]
Any updates? My eyes are burning, please give us darkmode ..

**Comment by JulianCataldo** [comment]
Rough start,

```css
:root {
	--color-canvas-100: #172554; /* blue-950 */
	--color-canvas: #1c1917; /* stone-900 */
	--color-canvas-tint: #171717; /* neutral-900 */
	--color-text: #f8fafc; /* slate-50 */
	--color-text-heading: #f8fafc; /* slate-50 */
	--color-text-paragraph: #f8fafc; /* slate-50 */
	--color-text-muted: #94a3b8; /* slate-50 */
}

.sl-overflow-y-auto {
	color-scheme: dark; /* For scrollbar */
}
```

https://tailwindcss.com/docs/customizing-colors

Just a bandaid for our poor eyes in the meantime :p It shows my hack method so other can do the same.

---


Computed:

<img width="763" alt="Screenshot 2023-05-06 at 12 53 32" src="https://user-images.githubusercontent.com/603498/236619914-93e58aa9-0c22-4f1b-95e6-cccab7ccc410.png">

<img width="1272" alt="Screenshot 2023-05-06 at 12 55 04" src="https://user-images.githubusercontent.com/603498/236620004-59f2a36f-35b1-4e73-9056-279fe1316439.png">
