### ISSUE TITLE
Wrong value range for string type as QUERY parameter

### ISSUE THREAD

**Issue by EugenMayer** [stoplightio/elements#1623]
```java
@Parameter(
    in = QUERY, style = SIMPLE, name = "title", description = "Search for a title with a left and right wildcard"
  )
```

consumed in the controller as 

```
final @RequestParam(name = "title", required = false) String title,
```

with the openAPI description

```yaml
     parameters:
      - name: "title"
        in: "query"
        description: "Search for a title with a left and right wildcard"
        required: false
        style: "simple"
        schema:
          type: "string"
```

```
title
string
Search for a title with a left and right wildcard

Comma Separated Values
```

There is no reason it should be an `Comma Separated Values` right?
