### ISSUE TITLE
Wrong rendering of array items definitions

### ISSUE THREAD

**Issue by ohjimijimijimi** [stoplightio/elements#1665]
## Describe the bug

Enum items of arrays are not rendered correctly. They miss the list of possible values. 

## To Reproduce

1. Given this OpenAPI document 
```yaml
proplist:
  type: array
  items:
    enum: 
      - p1
      - p2
      - p3
```
2. Render the schema
3. See 
    ![image](https://user-images.githubusercontent.com/766504/128141343-3cde7443-cc72-4488-8731-e3e1e7995af4.png)

OR 

1. Given this OpenAPI document 
```yaml
proplist:
  type: array
  items:
    type: string
    enum: 
      - p1
      - p2
      - p3
```
2. Render the schema
3. See 
    ![image](https://user-images.githubusercontent.com/766504/128141466-97501fce-bcf5-40a0-89f0-9e25e5f0b128.png)

## Expected behavior

The item definition should be rendered similarly to as done for objects. 
![Elements Create React App Template 2021-08-04 at 9 47 16 AM](https://user-images.githubusercontent.com/766504/128142721-f87890ec-d48b-40aa-a4c7-4d03a65d458f.jpg)

## Additional context
The same issue seems to be present for any definition of the array items. See how this schema is rendered
```yaml
proplist:
          type: array
          items:
            type: object
            properties: 
              item:
              type: string
              enum: 
                - p1
                - p2
                - p3
```

![image](https://user-images.githubusercontent.com/766504/128143383-dc4a86ea-7f94-41c7-a8b4-01a63e8d77fe.png)

**Environment (remove any that are not applicable):**
 - Library version: 7.0.0
 - OS: macOS Big Sur 11.3.1
 - Browser: Chrome 92.0.4515.107
 - Platform: web

<br><br><i>(related to <a href='https://stoplight.zendesk.com/agent/tickets/5867'>Zendesk ticket #5867</a>)<br>gz#5867</i>
