### ISSUE TITLE
Objects with all readOnly properties appearing in POST requests

### ISSUE THREAD

**Issue by steve-nay-sage** [stoplightio/elements#1735]
## Describe the bug

If an object within a schema only contains readOnly properties, the POST request display shows the object name with no properties underneath it. The object name should not be shown as it is not involved in POST requests.

## To Reproduce

1. We have an employee-expense schema that contains this object:

```
  nonReimbursable:
    type: object
    title: nonReimbursable
    properties:
      baseTotalEntered:
        type: number
        description: Non-reimbursable amount in base currency.
        readOnly: true
      reimbursementTotalEntered:
        type: number
        description: Total non-reimbursable amount.
        readOnly: true
```

Notice that both of the properties are readOnly: true.

The display of the POST command looks like this:

![image](https://user-images.githubusercontent.com/80782274/131381884-5c5cd781-530e-4971-9453-52b31fe6a8f0.png)

## Expected behavior

Objects that only contain readOnly:true properties should not appear in POST requests.

**Environment (remove any that are not applicable):**
 - OS: Windows 10
 - Browser: Chrome
 - Platform: web
