### ISSUE TITLE
Better support for custom security schemes and security scheme descriptions

### ISSUE THREAD

**Issue by jensljungblad** [stoplightio/elements#1794]
## Is your feature request related to a problem?

@philsturgeon asked me to open this after discussing on Slack.

Implementing a security scheme with a custom schema type should technically be possible. The OpenAPI spec only says the scheme SHOULD be registered in the IANA registry, not that it MUST.

So this should work:
```
components:
  securitySchemes:
    auth:
      name: Authorization
      in: header
      type: http
      schema: Custom-Type
      description: Enter the token with the `Custom-Type` prefix, e.g. `Custom-Type abc123`

secruity:
  - auth: []
```

However it only renders as: `“auth coming soon”`.

Related: Any description you add to a security scheme gets rendered, but it also renders Element's *default* description, which could have contradicting statements. If you provide your own description, I don't think Element should render the default one.

## Describe the solution you'd like

It would be great if it accepted the custom type!
