### ISSUE TITLE
Multiple values for authentication

### ISSUE THREAD

**Issue by GeitV** [stoplightio/elements#2023]
## Multiple Authentication parameters

As a web user, I'd like to do "Try It!" with authorization token and user ID, but it's not currently possible (I've checked even code of this project, and seems like this is not possibility, yet).

We are currently moving from using Postman to Stoplight. While moving, we got an issue, where we want to send `Authorization: Bearer token` and header `X-ACCOUNT-ID: 123`, as one user can have multiple accounts in our system.

Luckily, this is part of [OpenAPI spec](https://swagger.io/docs/specification/authentication/api-keys/) (multiple parameters by no leading dash between security parameters). However, this is not working in elements.

The ID is used as part of the authentication, so it's not really something we'd like to mark as parameter for each and every endpoint we have.

Example for this in OpenAPI
```
components:
  securitySchemes:
    jwtToken:
      type: http
      scheme: bearer
    accountId:
      type: apiKey
      in: header
      name: X-ACCOUNT-ID
security:
  - jwtToken: []
    accountId: []   # <-- no leading dash (-)
```
