### ISSUE TITLE
As a reader of the generated documentation, I want to see required scopes defined in the security key, so I know which ones my token needs for an operation to work

### ISSUE THREAD

**Issue by leolabs** [stoplightio/elements#2118]
## User Story Description

Example spec:

```yaml
paths:
  /search:
    get:
      summary: Search
      description: Search all available resources.
      operationId: search
      security:
        - bearerAuth:
          - users.list
          - apps.list
          - datasets.list
          - tags.list
```

Currently, the scopes defined here aren't shown in Elements:

<img width="788" alt="CleanShot 2022-04-18 at 13 36 13@2x" src="https://user-images.githubusercontent.com/541628/163802820-830744cf-122f-4c9d-8442-36d4ca9b1380.png">

It would be great to have them listed as part of the security section. A quick example of what this could look like:

<img width="760" alt="CleanShot 2022-04-18 at 13 40 29@2x" src="https://user-images.githubusercontent.com/541628/163803233-f33dadb1-a44e-4b74-b237-f97d8243f5b4.png">

## Acceptance Criteria

- [ ] Security scopes that are defined in the spec should be shown in the security box of operations

## Sprint Ready Checklist

- [ ] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Team has defined solution / steps to satisfy acceptance criteria
- [ ] Acceptance criteria is verifiable / testable
- [ ] External / 3rd Party dependencies identified

**Comment by Thomasdezeeuw** [comment]
Hey @mnaumanali94 we're using version 7.5.18 and this is how it looks for us:

<img width="460" alt="Screenshot 2022-05-13 at 14 55 10" src="https://user-images.githubusercontent.com/3159064/168287652-9553a134-5572-4188-9998-95051223dd2c.png">

Our spec is hosted here: https://www.slight.dev/api/reference/operations/search, the full yaml: https://www.slight.dev/http_spec.yaml. The relevant parts (I think) are the following:

```yaml
paths:
  /apps:
    get:
      security:
        - bearerAuth: ["apps.list", "apps.read"]
        - PAT: ["apps.list", "apps.read"]
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    PAT:
      type: http
      description: Personal Access Token (PAT).
      scheme: bearer
      bearerFormat: PAT
```

If I understand the spec correctly this should set the scopes for the security scheme, but maybe Elements processes it differently?
