### ISSUE TITLE
multipart/form-data array object is rendered as a textarea

### ISSUE THREAD

**Issue by albanhasa** [stoplightio/elements#2139]
I'm trying to create a POST request to enable upload of multiple files. 

```
      type: object
      properties:
        source_file:
          type: array
          description: File content
          items:
            type: string
            format: binary
```
The screenshot below is how the above element is rendered:
![image](https://user-images.githubusercontent.com/12504130/166423316-a06f9265-2264-4a8d-8d44-44ea9bfc4949.png)

Is there any custom configuration to follow in api design, to enable correct rendering of multiple file upload in this case?
