### ISSUE TITLE
Support for readonly $ref

### ISSUE THREAD

**Issue by rick-palmsens** [stoplightio/elements#2194]
readonly $ref is not supported properly even though there are ways to define it in OpenAPI

## Context

I have a model for an id, which I want to reference as readonly in other schemas.

## Current Behavior

I tried the pre 3.1 way:
```yaml
properties:
  id:
    readonly: true
    allOf:
      - $ref: ./Id.yaml
  createdOn:
    type: string
    format: date-time
    readOnly: true
  lastModifiedOn:
    type: string
    format: date-time
    readOnly: true
```

As well as the post 3.1 way:
```yaml
properties:
  id:
    readonly: true
    $ref: ./Id.yaml
  createdOn:
    type: string
    format: date-time
    readOnly: true
  lastModifiedOn:
    type: string
    format: date-time
    readOnly: true
```

## Expected Behavior

![image](https://user-images.githubusercontent.com/57390463/177734982-690b7aa9-46dd-4a88-b33c-77228cf50aa1.png)
