### ISSUE TITLE
Schema size error while example rendering

### ISSUE THREAD

**Issue by teluren** [stoplightio/elements#2238]
Dear colleagues,
I'm trying to generate the example preview over OpenAPI 3.0.x specification and getting an error:
>Example cannot be created for this schema
>Error: Schema size exceeded

The API response body for this example contains an array of objects with such a structure:
``` YAML
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Quote"
```
This Quote object is rather big - about 80 parameters, some of them with nested objects. The whole list is near the 250 parameters.
If I'm rendering only a single Quote schema object, an example generates correctly, but for the collection in the endpoint view falls. 

In smaller specifications, this array example works well. 
E.g., for this case:
``` YAML
  /user:
    get:
      summary: Get users list
      operationId: getUser
      responses:
        "200":
          description: User Created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
```
with this body:
``` YAML
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
```
Elements generates this example:
``` JSON
[
  {
    "id": 0,
    "firstName": "string",
    "lastName": "string",
    "email": "user@example.com",
    "dateOfBirth": "1997-10-31",
    "emailVerified": true,
    "createDate": "2019-08-24"
  }
]
```

Could you, please help, how can I increase this limit/schema size?
