### ISSUE TITLE
Read only fields are excluded from Webhook docs

### ISSUE THREAD

**Issue by browniebroke** [stoplightio/elements#2704]
## Context
We're using stoplight elements to documents our webhooks, so the events we provide on our services that our clients can consume. The schema of the events sometimes contains read-only properties, but these are not visible in the payload of the webhook in the docs, despite being present in the schema.  

## Current Behavior
Given the following schema: https://gist.github.com/browniebroke/5b7c5be806ae36e95232768ff04cefd6

```yaml
  schemas:
    Event:
      type: object
      properties:
        field_1:
          type: string
          readOnly: true
        field_2:
          type: string
```

Read only `field_1` is not documented:

![image](https://github.com/user-attachments/assets/ba3eb095-4613-413d-9333-b0da69fad059)

## Expected Behavior
Expected to see a `field_1` in the docs, above the `field_2` property. 

## Possible Workaround/Solution
No workaround found yet, except switching to another theme.

## Steps to Reproduce

See demo here: https://elements-demo.stoplight.io/?spec=https://gist.githubusercontent.com/browniebroke/5b7c5be806ae36e95232768ff04cefd6/raw/e7ae6de13d13f8f17b66aad743d35ff303600bcc/demo.yaml#/webhooks/Event-created/post 

Sample schema: https://gist.github.com/browniebroke/5b7c5be806ae36e95232768ff04cefd6

## Environment

- Version used: 8.4.2
- Environment name and version (e.g. Chrome 39, node.js 5.4): n/a
- Operating System and version (desktop or mobile): Desktop and mobile
- Link to your environment/workspace/project:
