### ISSUE TITLE
Try API calls with array query parameters (form style, exploded)

### ISSUE THREAD

**Issue by wanno-drijfhout** [stoplightio/elements#858]
**User story.**
As an API developer, I can "try" API calls from an API specification, so that I can verify correctness.

**Is your feature request related to a problem?**
Our ruby back-end requires query parameters of this form: `/api/something?client_ids[]=1&client_ids[]=2`. We expressed this with the following OpenAPI fragment:
```yaml
paths:
  '/api/something':
    parameters:
      - schema:
          type: string
        name: employee_id
        in: path
        required: true
    get:
      parameters:
        - schema:
            type: array
            uniqueItems: true
            items: 
              type: integer
          in: query
          name: 'client_ids[]'
          explode: true
          style: form
          allowReserved: true
```

Unfortunately, the "Try it" feature doesn't allow us to make proper API-calls, as you can see below:
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/2872972/107009279-18df2f80-6795-11eb-9cb7-05346e990ac0.png">
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/2872972/107010455-a5d6b880-6796-11eb-9a11-b95464386b19.png">

As specified before, the expected request URL is `/api/something?client_ids[]=1&client_ids[]=2` or `/api/something?client_ids%5B%5D=1&client_ids%5B%5D=2`.

**Describe the solution you'd like**
I'd like to know how to tweak the API specification to represent the required API calls properly, in case I've made a specification oopsie.

I'd like Stoplight Studio to support my use-case for making API calls. I need to pass multiple array values somehow.

I was unable to find this answer in [Stoplight documentation](https://meta.stoplight.io/docs/studio/docs/Design-and-Modeling/05-request-maker.md), so if an answer is available, we may want to document it.

**Additional context**
This very weird way of passing array values via query parameters is not that weird, sadly. It seems to be the norm for Ruby on Rails applications, as described [here](https://edgeguides.rubyonrails.org/action_controller_overview.html#hash-and-array-parameters).
